### ISSUE TITLE
footer issue, overlapping

### ISSUE THREAD

**Issue by PoisoN-ck** [pogor2p/alison#10]
<img width="2048" alt="Screenshot 2019-03-26 at 22 33 51" src="https://user-images.githubusercontent.com/37982929/55035128-66c27280-5017-11e9-89bb-ae2b2fe6b89b.png">
<img width="2048" alt="Screenshot 2019-03-26 at 22 34 22" src="https://user-images.githubusercontent.com/37982929/55035143-6de98080-5017-11e9-9a8c-4354b63316c0.png">

На всякий случай, у меня футер выглядит так, может WAD?

**Comment by Alex-Kostenko** [comment]
update. Check "home-page-fix" branches
