### ISSUE TITLE
Remove visible country code from form

### ISSUE THREAD

**Issue by PoisoN-ck** [pogor2p/alison#18]
<img width="562" alt="Screenshot 2019-03-28 at 21 13 44" src="https://user-images.githubusercontent.com/37982929/55189595-8b952200-519e-11e9-9a8f-b8b719626206.png">

Могу убрать код страны, оставить только флаг, места будет больше для самого телефона, что скажете?

**Comment by Alex-Kostenko** [comment]
Я максимально адаптировал с флагом. Как на меня, выглядит и так хорошо

**Comment by AlexeyPogorelov** [comment]
Давайте просто уберем стрелочку на дропдауне и немного сдвинем влево инпут с номером
