### ISSUE TITLE
header-background issue

### ISSUE THREAD

**Issue by PoisoN-ck** [pogor2p/alison#9]
<img width="2048" alt="Screenshot 2019-03-26 at 22 29 38" src="https://user-images.githubusercontent.com/37982929/55034893-d84df100-5016-11e9-989b-cde90cdc1740.png">
<img width="2048" alt="Screenshot 2019-03-26 at 22 30 03" src="https://user-images.githubusercontent.com/37982929/55034916-e7cd3a00-5016-11e9-849f-1871edafaa9b.png">
<img width="2048" alt="Screenshot 2019-03-26 at 22 30 51" src="https://user-images.githubusercontent.com/37982929/55034994-1f3be680-5017-11e9-97a1-62600803da4c.png">

Кажется, картинка не тянется, название другое

**Comment by Alex-Kostenko** [comment]
repaired
